[log]
print_level = 1
print_step = 1
[mode]
mode = "UHFr"
[mode.param]
Nsite = 6
Ncond = 6
#2Sz = 0
IterationMax = 1000
EPS = 8
Mix = 0.5
RndSeed = 123456789
T = 0.0
#ene_cutoff = 1.0e+2
[file]
[file.input]
path_to_input = "./"
onebodyg = "greenone.def"
[file.input.interaction]
trans = "trans.def"
coulombintra = "coulombintra.def"
locspin = "locspn.def"
onebodyg = "greenone.def"
[file.output]
path_to_output = "output"
energy = "energy.dat"
eigen = "eigen.dat"
green = "green.dat"
