[log]
  print_level = 1

[mode]
  mode = "UHFk"
  flag_fock = true

[mode.param]
  Nsite = 8
  2Sz = 0
  Ncond = 1280
  IterationMax = 20
  EPS = 8
  Mix = 0.5
  RndSeed = 123456789
  # EpsSlater = 6
  # NMPTrans = 0
  # CDataFileHead = "zvo"
  # CParaFileHead = "zqp"
  # ene_cutoff = 1.0e+2
  T = 1.0
  CellShape = [ 8, 8, 8 ]

[file]
[file.input]
  path_to_input = ""
  # namelist = "namelist.def"
  # initial = "green_init.dat.npz"

[file.input.interaction]
  path_to_input = "dir-model"
  Geometry = "zvo_geom.dat"
  Transfer = "zvo_hr.dat"
  Hund = "zvo_jr.dat"
  # Coulomb = "zvo_ur.dat"
  # CoulombIntra = "coulomb_intra.dat"
  # CoulombInter = "coulomb_inter.dat"
  # Ising = "ising.dat"
  # Exchange = "exchange.dat"
  # PairLift = "pairlift.dat"
  # PairHop = "pairhop.dat"

[file.output]
  path_to_output = "output"
  energy = "energy.dat"
  eigen = "eigen.dat"
  green = "green.dat"
