[log]
  print_level = 1

[mode]
  mode = "UHFk"
  # flag_fock = True

[mode.param]
  # 2Sz = 0
  Ncond = 128
  IterationMax = 1000
  EPS = 8
  Mix = 0.5
  RndSeed = 123456789
  # ene_cutoff = 1.0e+2
  T = 0.0
  CellShape = [ 8, 8, 8 ]
  #SubShape = [ 2, 2, 2 ]

[file]
[file.input]
  path_to_input = ""
  # initial = "green_init.dat.npz"

[file.input.interaction]
  path_to_input = "../dir-model"
  Geometry = "zvo_geom.dat"
  Transfer = "zvo_hr.dat"
  Hund = "zvo_jr.dat"
  Coulomb = "zvo_ur.dat"

[file.output]
  path_to_output = "output"
  energy = "energy.dat"
  eigen = "eigen.dat"
  green = "green.dat"
