[log]
print_level = 0
print_step = 1

[mode]
mode = "UHFk"

[mode.param]
Ncond = 1728
IterationMax = 1000
EPS = 10
Mix = 0.5
RndSeed = 123456789
T = 0.2
CellShape = [
    12,
    12,
    12,
]
SubShape = [
    2,
    2,
    2,
]

[file.input]
path_to_input = ""
initial = "green_init.dat.npz"

[file.input.interaction]
path_to_input = "./"
Geometry = "geom.dat"
Transfer = "transfer.dat"
CoulombIntra = "coulombintra.dat"

[file.output]
path_to_output = "output_T0.2"
energy = "energy.dat"
eigen = "eigen.dat"
green = "green.dat"
