[log]
  print_level = 1

[mode]
  mode = "RPA"

[mode.param]
  T = 0.01
  CellShape = [128,128,1]
  SubShape = [1,1,1]
  filling = 0.75
  Nmat = 4096
  matsubara_frequency = "center"
[file]
[file.input]
  path_to_input = "../onsite/output"
  chi0q_init = "chi0q.npz"
  
[file.input.interaction]
  path_to_input = "./"
  Geometry = "geom.dat"
  Transfer = "transfer.dat"
  CoulombInter = "coulombinter.dat"

[file.output]
  path_to_output = "output"
  chiq = "chiq"
  matsubara_frequency = "all"  # default
