[log]
  print_level = 1
  print_step = 10
[mode]
  mode = "UHFk"
[mode.param]
  # 2Sz = 0
  Ncond = 510
  IterationMax = 10000
  EPS = 8
  Mix = 0.5
  RndSeed = 123456789
  T = 0.0
  CellShape = [ 16 , 16 , 1 ]
  Subshape  = [ 1 , 1 , 1 ]
[file]
[file.input]
  path_to_input = ""
[file.input.interaction]
  path_to_input = "./"
  Geometry = "geom.dat"
  Transfer = "transfer.dat"
  CoulombInter = "coulombintra.dat"
[file.output]
  path_to_output = "output"
  energy = "energy.dat"
  eigen = "eigen"
  green = "green"
