[log]
  print_level = 1

[mode]
  mode = "RPA"
  calc_scheme = "reduced"
[mode.param]
  T = 0.01
  CellShape = [64,64,1]
  SubShape = [1,1,1]
  filling = 0.75
  Nmat = 1024
  matsubara_frequency = "center"
[file]
[file.input.interaction]
  path_to_input = "./"
  Geometry = "geom.dat"
  Transfer = "transfer.dat"
  CoulombIntra = "coulombintra_U0.4.dat"
[file.output]
  path_to_output = "output"
  chiq = "chiq_U0.4"
  chi0q = "chi0q"
  matsubara_frequency = "center"  # default
